In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("House-Price.csv")

In [3]:
df.head()

price  resid_area  air_qual  room_num   age  dist1  dist2  dist3  dist4  \
0   24.0       32.31     0.538     6.575  65.2   4.35   3.81   4.18   4.01   
1   21.6       37.07     0.469     6.421  78.9   4.99   4.70   5.12   5.06   
2   34.7       37.07     0.469     7.185  61.1   5.03   4.86   5.01   4.97   
3   33.4       32.18     0.458     6.998  45.8   6.21   5.93   6.16   5.96   
4   36.2       32.18     0.458     7.147  54.2   6.16   5.86   6.37   5.86   

   teachers  poor_prop airport  n_hos_beds  n_hot_rooms waterbody  rainfall  \
0      24.7       4.98     YES       5.480      11.1920     River        23   
1      22.2       9.14      NO       7.332      12.1728      Lake        42   
2      22.2       4.03      NO       7.394     101.1200      None        38   
3      21.3       2.94     YES       9.268      11.2672      Lake        45   
4      21.3       5.33      NO       8.824      11.2896      Lake        55   

  bus_ter     parks  Sold  
0     YES  0.049347     0  
1     YES  0.046146     1  
2     YES  0.045764     0  
3     YES  0.047151     0  
4     YES  0.039474     0

In [4]:
df.shape

(506, 19)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   price        506 non-null    float64
 1   resid_area   506 non-null    float64
 2   air_qual     506 non-null    float64
 3   room_num     506 non-null    float64
 4   age          506 non-null    float64
 5   dist1        506 non-null    float64
 6   dist2        506 non-null    float64
 7   dist3        506 non-null    float64
 8   dist4        506 non-null    float64
 9   teachers     506 non-null    float64
 10  poor_prop    506 non-null    float64
 11  airport      506 non-null    object 
 12  n_hos_beds   498 non-null    float64
 13  n_hot_rooms  506 non-null    float64
 14  waterbody    506 non-null    object 
 15  rainfall     506 non-null    int64  
 16  bus_ter      506 non-null    object 
 17  parks        506 non-null    float64
 18  Sold         506 non-null    int64  
dtypes: float

In [6]:
df.n_hos_beds=df.n_hos_beds.fillna(df.n_hos_beds.mean())

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   price        506 non-null    float64
 1   resid_area   506 non-null    float64
 2   air_qual     506 non-null    float64
 3   room_num     506 non-null    float64
 4   age          506 non-null    float64
 5   dist1        506 non-null    float64
 6   dist2        506 non-null    float64
 7   dist3        506 non-null    float64
 8   dist4        506 non-null    float64
 9   teachers     506 non-null    float64
 10  poor_prop    506 non-null    float64
 11  airport      506 non-null    object 
 12  n_hos_beds   506 non-null    float64
 13  n_hot_rooms  506 non-null    float64
 14  waterbody    506 non-null    object 
 15  rainfall     506 non-null    int64  
 16  bus_ter      506 non-null    object 
 17  parks        506 non-null    float64
 18  Sold         506 non-null    int64  
dtypes: float

In [8]:
df=pd.get_dummies(df)

In [9]:
df.head()

price  resid_area  air_qual  room_num   age  dist1  dist2  dist3  dist4  \
0   24.0       32.31     0.538     6.575  65.2   4.35   3.81   4.18   4.01   
1   21.6       37.07     0.469     6.421  78.9   4.99   4.70   5.12   5.06   
2   34.7       37.07     0.469     7.185  61.1   5.03   4.86   5.01   4.97   
3   33.4       32.18     0.458     6.998  45.8   6.21   5.93   6.16   5.96   
4   36.2       32.18     0.458     7.147  54.2   6.16   5.86   6.37   5.86   

   teachers  ...  rainfall     parks  Sold  airport_NO  airport_YES  \
0      24.7  ...        23  0.049347     0           0            1   
1      22.2  ...        42  0.046146     1           1            0   
2      22.2  ...        38  0.045764     0           1            0   
3      21.3  ...        45  0.047151     0           0            1   
4      21.3  ...        55  0.039474     0           1            0   

   waterbody_Lake  waterbody_Lake and River  waterbody_None  waterbody_River  \
0               0                         0               0                1   
1               1                         0               0                0   
2               0                         0               1                0   
3               1                         0               0                0   
4               1                         0               0                0   

   bus_ter_YES  
0            1  
1            1  
2            1  
3            1  
4            1  

[5 rows x 23 columns]

In [10]:
del df['waterbody_Lake and River']

In [11]:
df.head()

price  resid_area  air_qual  room_num   age  dist1  dist2  dist3  dist4  \
0   24.0       32.31     0.538     6.575  65.2   4.35   3.81   4.18   4.01   
1   21.6       37.07     0.469     6.421  78.9   4.99   4.70   5.12   5.06   
2   34.7       37.07     0.469     7.185  61.1   5.03   4.86   5.01   4.97   
3   33.4       32.18     0.458     6.998  45.8   6.21   5.93   6.16   5.96   
4   36.2       32.18     0.458     7.147  54.2   6.16   5.86   6.37   5.86   

   teachers  ...  n_hot_rooms  rainfall     parks  Sold  airport_NO  \
0      24.7  ...      11.1920        23  0.049347     0           0   
1      22.2  ...      12.1728        42  0.046146     1           1   
2      22.2  ...     101.1200        38  0.045764     0           1   
3      21.3  ...      11.2672        45  0.047151     0           0   
4      21.3  ...      11.2896        55  0.039474     0           1   

   airport_YES  waterbody_Lake  waterbody_None  waterbody_River  bus_ter_YES  
0            1               0               0                1            1  
1            0               1               0                0            1  
2            0               0               1                0            1  
3            1               1               0                0            1  
4            0               1               0                0            1  

[5 rows x 22 columns]

In [12]:
x=df.loc[:,df.columns!='Sold']

In [13]:
y=df['Sold']

In [14]:
x.head()

price  resid_area  air_qual  room_num   age  dist1  dist2  dist3  dist4  \
0   24.0       32.31     0.538     6.575  65.2   4.35   3.81   4.18   4.01   
1   21.6       37.07     0.469     6.421  78.9   4.99   4.70   5.12   5.06   
2   34.7       37.07     0.469     7.185  61.1   5.03   4.86   5.01   4.97   
3   33.4       32.18     0.458     6.998  45.8   6.21   5.93   6.16   5.96   
4   36.2       32.18     0.458     7.147  54.2   6.16   5.86   6.37   5.86   

   teachers  ...  n_hos_beds  n_hot_rooms  rainfall     parks  airport_NO  \
0      24.7  ...       5.480      11.1920        23  0.049347           0   
1      22.2  ...       7.332      12.1728        42  0.046146           1   
2      22.2  ...       7.394     101.1200        38  0.045764           1   
3      21.3  ...       9.268      11.2672        45  0.047151           0   
4      21.3  ...       8.824      11.2896        55  0.039474           1   

   airport_YES  waterbody_Lake  waterbody_None  waterbody_River  bus_ter_YES  
0            1               0               0                1            1  
1            0               1               0                0            1  
2            0               0               1                0            1  
3            1               1               0                0            1  
4            0               1               0                0            1  

[5 rows x 21 columns]

In [15]:
y.head()

0    0
1    1
2    0
3    0
4    0
Name: Sold, dtype: int64

### Train_Test_Split

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [18]:
x_train.head()

price  resid_area  air_qual  room_num   age  dist1  dist2  dist3  dist4  \
220   26.7       36.20     0.507     6.951  88.5   3.03   2.72   3.03   2.66   
71    21.7       40.81     0.413     5.961  17.5   5.44   5.20   5.42   5.09   
240   27.0       34.93     0.428     6.897  54.3   6.49   6.13   6.40   6.32   
6     22.9       37.87     0.524     6.012  66.6   5.87   5.47   5.70   5.20   
417   10.4       48.10     0.679     5.304  89.1   1.73   1.39   1.81   1.67   

     teachers  ...  n_hos_beds  n_hot_rooms  rainfall     parks  airport_NO  \
220      22.6  ...       8.734      11.2136        23  0.053540           1   
71       20.8  ...      10.034      13.1736        46  0.039985           1   
240      23.4  ...      10.240      11.2160        24  0.038641           0   
6        24.8  ...       6.958      12.1832        41  0.052170           0   
417      19.8  ...       8.608      15.0832        60  0.058835           0   

     airport_YES  waterbody_Lake  waterbody_None  waterbody_River  bus_ter_YES  
220            0               0               0                1            1  
71             0               0               0                0            1  
240            1               0               1                0            1  
6              1               0               0                1            1  
417            1               0               0                0            1  

[5 rows x 21 columns]

In [19]:
x_train.shape

(404, 21)

In [20]:
y_train.head()

220    0
71     0
240    0
6      1
417    0
Name: Sold, dtype: int64

In [21]:
y_train.shape

(404,)

In [22]:
from sklearn.linear_model import LogisticRegression

In [25]:
clf_lr=LogisticRegression()

In [26]:
clf_lr.fit(x_train,y_train)

C:\Users\sandi\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [27]:
y_test_pred=clf_lr.predict(x_test)

In [28]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [29]:
confusion_matrix(y_test,y_test_pred)

array([[39, 19],
       [15, 29]], dtype=int64)

In [31]:
accuracy_score(y_test,y_test_pred)

0.6666666666666666

### K-Nearest Neighbors

In [35]:
from sklearn.preprocessing import StandardScaler

In [40]:
scaler = preprocessing.StandardScaler().fit(x_train)

In [41]:
x_train_s= scaler.transform(x_train)

In [42]:
x_test_s=scaler.transform(x_test)

In [43]:
from sklearn.neighbors import KNeighborsClassifier

In [45]:
clf_knn_1=KNeighborsClassifier(n_neighbors=1)

In [48]:
clf_knn_1.fit(x_train_s,y_train)

KNeighborsClassifier(n_neighbors=1)

In [50]:
y_test_pred_s=clf_knn_1.predict(x_test_s)

In [51]:
confusion_matrix(y_test,y_test_pred_s)

array([[34, 24],
       [21, 23]], dtype=int64)

In [52]:
accuracy_score(y_test,y_test_pred_s)

0.5588235294117647

In [53]:
clf_knn_3=KNeighborsClassifier(n_neighbors=3)

In [54]:
clf_knn_3.fit(x_train_s,y_train)

KNeighborsClassifier(n_neighbors=3)

In [55]:
y_test_pred_s=clf_knn_1.predict(x_test_s)

In [56]:
confusion_matrix(y_test,y_test_pred_s)

array([[34, 24],
       [21, 23]], dtype=int64)

In [57]:
accuracy_score(y_test,y_test_pred_s)

0.5588235294117647

In [61]:
from sklearn.model_selection import GridSearchCV

In [62]:
params={'n_neighbors' :[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]}

In [63]:
grid_search_cv = GridSearchCV(KNeighborsClassifier(),params)

In [65]:
grid_search_cv.fit(x_train_s,y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]})

In [67]:
grid_search_cv.best_params_

{'n_neighbors': 6}

In [68]:
optimised_KNN = grid_search_cv.best_estimator_

In [72]:
y_test_pred_new = optimised_KNN.predict(x_test_s)

In [73]:
confusion_matrix(y_test,y_test_pred_new)

array([[38, 20],
       [26, 18]], dtype=int64)

In [74]:
accuracy_score(y_test,y_test_pred_new)

0.5490196078431373